# Generated by Django 3.2.4 on 2021-06-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('num_habitacion', models.FloatField(blank=True, null=True)),
                ('piso', models.CharField(blank=True, max_length=2, null=True)),
                ('num_camas', models.FloatField(blank=True, null=True)),
                ('num_cuartos', models.FloatField(blank=True, null=True)),
                ('valor_noche', models.FloatField(blank=True, null=True)),
                ('capacidad_pasajeros', models.FloatField(blank=True, null=True)),
                ('disponibilidad', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_plato', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=40)),
                ('precio_plato', models.IntegerField()),
                ('descripcion_plato', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
    ]
